# Generated by Django 6.1.1 on 2026-10-02 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_sem_consumo', models.PositiveIntegerField()),
                ('gasto_medio_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_consumo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de consumo',
                'verbose_name_plural': 'Históricos de consumo',
                'db_table': 'historico_consumo',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
