# Generated by Django 6.1.1 on 2026-10-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='reunioes/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de reunião',
                'verbose_name_plural': 'Tipos de reunião',
                'db_table': 'tipo_reuniao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('modalidade', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('hibrida', 'Híbrida')], default='online', max_length=20)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='reunioes.tiporeuniao')),
            ],
            options={
                'verbose_name': 'Programação de reunião',
                'verbose_name_plural': 'Programações de reunião',
                'db_table': 'programacao_reuniao',
                'ordering': ['dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('tipo_reuniao', 'dia_semana', 'hora_inicio'), name='unique_programacao_reuniao')],
            },
        ),
    ]
